### ISSUE TITLE
Valve Actuation Counter

### ISSUE THREAD

**Issue by jirhiker** [NMGRL/pychron#1779]
Add a valve actuation counter file. add flag to valve.xml to define which valves to count

every actuation open the counter file and update.
display total actuations in Extraction Line window
load actuation counts when constructing valves
add ability to reset counts. reset counts backs up current counts first

```
<valve> A
<count>True</count>
</valve>
```

example counter file
```
A:
  actuations: 1231
  last_change:  12/12/19 10:10.324
B: 
  actuations: 1234
  last_change:  12/13/19 11:10.553
```

example of counter file after resetting A on 12/12/19 10:20.402

```
A:
  actuations: 0
  last_change:  
B: 
  actuations: 1234
  last_change:  12/13/19 11:10.553
A1212191020402:
  actuations: 1231
  last_change:  12/12/19 10:10.324
```
